# Generated by Django 6.0.3 on 2026-05-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userpushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='image_url',
            field=models.CharField(blank=True, help_text='URL of the gadget image', max_length=500, null=True),
        ),
    ]
