# Generated by Django 6.0.3 on 2026-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gadget_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active', 'overdue'])), fields=('gadget',), name='unique_active_gadget_rental'),
        ),
    ]
